services:
  database:
    image: mongo
    command: mongod --quiet
    ports:
      - "27017:27017"

  controller:
    build: ./controller
    ports:
      - "80:3000"
      - "5000:5000"
    depends_on:
      - database
    volumes:
      - ./controller:/app
      - /app/node_modules
  
  worker:
    build: ./worker
    depends_on:
      - controller
    environment:
      - CONTROLLER_URL=http://controller:3000
      - TIME_BETWEEN_TASKS=1
