services:
  database:
    image: mongo
    command: mongod --quiet --port 30017
    ports:
      - "30017:30017"

  controller:
    build: ./controller
    ports:
      - "80:3000"
      - "5000:5000"
    depends_on:
      - database
    volumes:
      - ./controller:/app
      - /app/node_modules
    environment:
      - DATABASE_URL=mongodb://database:30017
      - FRONTEND_PORT=3000
  
  worker:
    build: ./worker
    depends_on:
      - controller
    ports:
      - "11111:11111"
    environment:
      - CONTROLLER_URL=http://controller:3000
      - TIME_BETWEEN_TASKS=1
      - PORT=11111
      - DEBUG=0
