apiVersion: v1
kind: Service
metadata:
  name: controller-service
  labels:
    app: controller
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: controller
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: controller-ingress
spec:
  rules:
  - host: controller.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: controller-service
            port:
              number: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-deployment
  labels:
    app: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          value: mongodb://database-service:27017
        - name: FRONTEND_PORT
          value: "3000"
        name: controller
        image: uplink036/controller
        ports:
        - containerPort: 3000
          protocol: TCP
---