apiVersion: v1
kind: Service
metadata:
  labels:
    app: worker
  name: worker
spec:
  ports:
    - name: healthpoint
      port: 11111
      targetPort: 11111
  selector:
    app: worker
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: worker-ingress
spec:
  rules:
  - host: worker.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: worker
            port:
              number: 11111
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - env:
            - name: CONTROLLER_URL
              value: http://controller-service:5000
            - name: DEBUG
              value: "1"
            - name: PORT
              value: "11111"
            - name: TIME_BETWEEN_TASKS
              value: "1"
          image: uplink036/worker
          name: worker
          ports:
            - containerPort: 11111
              protocol: TCP