name: CodeFormat

on:
  push:
  pull_request:

jobs:
  linter:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    
    - name: Install dependencies
      run: |
        cd controller
        npm install
    
    - name: Run ESLint
      run: |
        cd controller
        npm run lint

    - name: Run prettier
      run: |
        cd controller
        npm run format:check